---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blue
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./blue
  prune: true
  sourceRef:
    kind: GitRepository
    name: blue
  targetNamespace: default
