---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: green
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./green
  prune: true
  sourceRef:
    kind: GitRepository
    name: green
  targetNamespace: default
