---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: python-demo-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: python-image
  policy:
    numerical:
      order: asc
