---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: python-flask
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: python-repo-auth
  url: ssh://git@github.com/ksnithya/eks-python-demo.git
